services:
  rviz_novnc:
    build:
      context: .
      dockerfile: Dockerfile.rviz-novnc
    container_name: dah-rviz-novnc
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-17}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
