services:
  rosbot_sim:
    image: husarion/rosbot-gazebo:humble
    container_name: dah-rosbot-sim
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-17}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -lc "
      source /opt/ros/humble/setup.bash &&
      source /ros2_ws/install/setup.bash &&
      ros2 launch rosbot_gazebo simulation.launch.py
      robot_model:=rosbot
      rviz:=False
      gz_headless_mode:=True
      gz_log_level:=1
      "
